### ISSUE TITLE
SMS injection

### ISSUE THREAD

**Issue by Dastgsm** [SysSec-KAIST/DoLTEst#1]
hello,

Is it possible to make sms_injection with this? how could this sms_injection process?

Chears,

**Comment by unrloay2** [comment]
Yes, 
DoLTEst includes test cases for Downlink NAS Transport message, which is used for SMS over NAS. 
If your test UE has a vulnerability for handling that msg, you will receive SMS. 
For the procedure details, I recommend you refer specs (start from TS 24.301) or blogs about SMS over NAS / Downlink NAS Transport.
